[workspace]
resolver = "2"
members = ["crates/raven"]

[workspace.package]
version = "0.1.1"
authors = ["Jonathan Marc Bearak <jbearak@gmail.com>"]
edition = "2021"
license = "GPL-3.0"
rust-version = "1.75"

[workspace.dependencies]
tower-lsp = "0.20"